//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhmK22CNT3Lss07.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NhmK22CNTT3Lesson7Entities : DbContext
    {
        public NhmK22CNTT3Lesson7Entities()
            : base("name=NhmK22CNTT3Lesson7Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NhmKhoa> NhmKhoas { get; set; }
        public virtual DbSet<nhmsinhvien4> nhmsinhvien4 { get; set; }
    }
}
