//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NhmK22CNT3Lss07.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class nhmsinhvien4
    {
        public string NhmMaSV { get; set; }
        public string NhmHoSV { get; set; }
        public string NhmTenSV { get; set; }
        public string NhmNgaySinh { get; set; }
        public string NhmPhai { get; set; }
        public string NhmPhone { get; set; }
        public string NhmEmail { get; set; }
        public string NhmMaKH { get; set; }
    
        public virtual NhmKhoa NhmKhoa { get; set; }
    }
}
